# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'ui_demo.ui'
##
## Created by: Qt User Interface Compiler version 6.8.3
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QComboBox, QFrame, QHBoxLayout,
    QLabel, QMainWindow, QMenuBar, QPushButton,
    QSizePolicy, QStatusBar, QWidget)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(1379, 883)
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.layoutWidget = QWidget(self.centralwidget)
        self.layoutWidget.setObjectName(u"layoutWidget")
        self.layoutWidget.setGeometry(QRect(10, 0, 931, 81))
        self.horizontalLayout = QHBoxLayout(self.layoutWidget)
        self.horizontalLayout.setSpacing(4)
        self.horizontalLayout.setObjectName(u"horizontalLayout")
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.btn_ref = QPushButton(self.layoutWidget)
        self.btn_ref.setObjectName(u"btn_ref")
        font = QFont()
        font.setPointSize(10)
        self.btn_ref.setFont(font)
        self.btn_ref.setStyleSheet(u"background-color: rgb(255, 255, 255);")
        icon = QIcon()
        icon.addFile(u"../../plc/Icons/power_on.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.btn_ref.setIcon(icon)

        self.horizontalLayout.addWidget(self.btn_ref)

        self.label = QLabel(self.layoutWidget)
        self.label.setObjectName(u"label")
        self.label.setMaximumSize(QSize(100, 100))
        font1 = QFont()
        font1.setPointSize(14)
        self.label.setFont(font1)

        self.horizontalLayout.addWidget(self.label)

        self.camlist = QComboBox(self.layoutWidget)
        self.camlist.setObjectName(u"camlist")
        self.camlist.setMinimumSize(QSize(100, 0))
        self.camlist.setMaximumSize(QSize(200, 16777215))
        self.camlist.setStyleSheet(u"background-color: rgb(255, 255, 255);")

        self.horizontalLayout.addWidget(self.camlist)

        self.pick_cam = QComboBox(self.layoutWidget)
        self.pick_cam.addItem("")
        self.pick_cam.addItem("")
        self.pick_cam.addItem("")
        self.pick_cam.setObjectName(u"pick_cam")
        self.pick_cam.setMinimumSize(QSize(100, 0))
        self.pick_cam.setMaximumSize(QSize(200, 16777215))
        self.pick_cam.setStyleSheet(u"background-color: rgb(255, 255, 255);")

        self.horizontalLayout.addWidget(self.pick_cam)

        self.btn_start = QPushButton(self.layoutWidget)
        self.btn_start.setObjectName(u"btn_start")
        self.btn_start.setFont(font)
        self.btn_start.setStyleSheet(u"background-color: rgb(255, 255, 255);")
        self.btn_start.setIcon(icon)

        self.horizontalLayout.addWidget(self.btn_start)

        self.btn_stop = QPushButton(self.layoutWidget)
        self.btn_stop.setObjectName(u"btn_stop")
        self.btn_stop.setFont(font)
        self.btn_stop.setStyleSheet(u"background-color: rgb(255, 255, 255);")
        icon1 = QIcon()
        icon1.addFile(u"../../plc/Icons/power-off.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.btn_stop.setIcon(icon1)

        self.horizontalLayout.addWidget(self.btn_stop)

        self.horizontalLayoutWidget = QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setObjectName(u"horizontalLayoutWidget")
        self.horizontalLayoutWidget.setGeometry(QRect(10, 80, 481, 411))
        self.horizontalLayout_3 = QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout_3.setObjectName(u"horizontalLayout_3")
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.disp_main_in = QLabel(self.horizontalLayoutWidget)
        self.disp_main_in.setObjectName(u"disp_main_in")
        self.disp_main_in.setEnabled(True)
        self.disp_main_in.setMaximumSize(QSize(640, 480))
        self.disp_main_in.setStyleSheet(u"background-color: rgb(246, 247, 247);")
        self.disp_main_in.setAlignment(Qt.AlignCenter)

        self.horizontalLayout_3.addWidget(self.disp_main_in)

        self.horizontalLayoutWidget_4 = QWidget(self.centralwidget)
        self.horizontalLayoutWidget_4.setObjectName(u"horizontalLayoutWidget_4")
        self.horizontalLayoutWidget_4.setGeometry(QRect(940, 210, 431, 281))
        self.horizontalLayout_5 = QHBoxLayout(self.horizontalLayoutWidget_4)
        self.horizontalLayout_5.setObjectName(u"horizontalLayout_5")
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.disp_main_check = QLabel(self.horizontalLayoutWidget_4)
        self.disp_main_check.setObjectName(u"disp_main_check")
        self.disp_main_check.setMaximumSize(QSize(640, 480))
        self.disp_main_check.setStyleSheet(u"background-color: rgb(246, 247, 247);")
        self.disp_main_check.setAlignment(Qt.AlignCenter)

        self.horizontalLayout_5.addWidget(self.disp_main_check)

        self.horizontalLayoutWidget_5 = QWidget(self.centralwidget)
        self.horizontalLayoutWidget_5.setObjectName(u"horizontalLayoutWidget_5")
        self.horizontalLayoutWidget_5.setGeometry(QRect(490, 80, 451, 411))
        self.horizontalLayout_6 = QHBoxLayout(self.horizontalLayoutWidget_5)
        self.horizontalLayout_6.setObjectName(u"horizontalLayout_6")
        self.horizontalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.disp_main_out = QLabel(self.horizontalLayoutWidget_5)
        self.disp_main_out.setObjectName(u"disp_main_out")
        self.disp_main_out.setMaximumSize(QSize(640, 480))
        self.disp_main_out.setStyleSheet(u"background-color: rgb(246, 247, 247);")
        self.disp_main_out.setAlignment(Qt.AlignCenter)

        self.horizontalLayout_6.addWidget(self.disp_main_out)

        self.BT_VAO = QPushButton(self.centralwidget)
        self.BT_VAO.setObjectName(u"BT_VAO")
        self.BT_VAO.setGeometry(QRect(940, 490, 231, 71))
        font2 = QFont()
        font2.setFamilies([u"Arial"])
        font2.setPointSize(16)
        font2.setBold(True)
        self.BT_VAO.setFont(font2)
        self.BT_VAO.setLayoutDirection(Qt.LeftToRight)
        self.BT_VAO.setAutoFillBackground(False)
        self.BT_VAO.setStyleSheet(u"color: rgb(0, 0, 0);\n"
"background-color: rgb(0, 255, 0);")
        self.BT_RA = QPushButton(self.centralwidget)
        self.BT_RA.setObjectName(u"BT_RA")
        self.BT_RA.setGeometry(QRect(1170, 490, 201, 71))
        self.BT_RA.setFont(font2)
        self.BT_RA.setLayoutDirection(Qt.LeftToRight)
        self.BT_RA.setAutoFillBackground(False)
        self.BT_RA.setStyleSheet(u"color: rgb(0, 0, 0);\n"
"background-color: rgb(0, 255, 0);")
        self.lb_con_lai = QLabel(self.centralwidget)
        self.lb_con_lai.setObjectName(u"lb_con_lai")
        self.lb_con_lai.setGeometry(QRect(1060, 0, 85, 50))
        font3 = QFont()
        font3.setFamilies([u"Arial"])
        font3.setPointSize(20)
        font3.setBold(True)
        self.lb_con_lai.setFont(font3)
        self.lb_con_lai.setStyleSheet(u"background-color: rgb(255, 255, 255);")
        self.lb_con_lai.setFrameShape(QFrame.Panel)
        self.lb_con_lai.setAlignment(Qt.AlignCenter)
        self.label_11 = QLabel(self.centralwidget)
        self.label_11.setObjectName(u"label_11")
        self.label_11.setGeometry(QRect(950, 0, 101, 51))
        font4 = QFont()
        font4.setFamilies([u"Arial"])
        font4.setPointSize(16)
        font4.setBold(True)
        font4.setItalic(False)
        self.label_11.setFont(font4)
        self.label_11.setStyleSheet(u"background-color: rgb(255, 255, 255);\n"
"\n"
"")
        self.label_18 = QLabel(self.centralwidget)
        self.label_18.setObjectName(u"label_18")
        self.label_18.setGeometry(QRect(1160, 0, 101, 51))
        self.label_18.setFont(font4)
        self.label_18.setStyleSheet(u"background-color: rgb(255, 255, 255);\n"
"\n"
"")
        self.lb_so_xe = QLabel(self.centralwidget)
        self.lb_so_xe.setObjectName(u"lb_so_xe")
        self.lb_so_xe.setGeometry(QRect(1270, 0, 91, 51))
        self.lb_so_xe.setFont(font3)
        self.lb_so_xe.setStyleSheet(u"background-color: rgb(255, 255, 255);")
        self.lb_so_xe.setFrameShape(QFrame.Panel)
        self.lb_so_xe.setAlignment(Qt.AlignCenter)
        self.lb_tb_2 = QLabel(self.centralwidget)
        self.lb_tb_2.setObjectName(u"lb_tb_2")
        self.lb_tb_2.setGeometry(QRect(940, 60, 431, 71))
        font5 = QFont()
        font5.setFamilies([u"Arial"])
        font5.setPointSize(20)
        font5.setBold(True)
        font5.setItalic(False)
        self.lb_tb_2.setFont(font5)
        self.lb_tb_2.setStyleSheet(u"background-color: rgb(85, 255, 0);\n"
"\n"
"")
        self.lb_tb_2.setFrameShape(QFrame.Panel)
        self.lb_tb_2.setAlignment(Qt.AlignCenter)
        self.thoi_gian = QLabel(self.centralwidget)
        self.thoi_gian.setObjectName(u"thoi_gian")
        self.thoi_gian.setGeometry(QRect(940, 130, 431, 81))
        self.thoi_gian.setFont(font3)
        self.thoi_gian.setStyleSheet(u"background-color: rgb(255, 255, 255);")
        self.thoi_gian.setFrameShape(QFrame.Panel)
        self.thoi_gian.setAlignment(Qt.AlignCenter)
        self.lb_bien_vao = QLabel(self.centralwidget)
        self.lb_bien_vao.setObjectName(u"lb_bien_vao")
        self.lb_bien_vao.setGeometry(QRect(10, 490, 481, 71))
        self.lb_bien_vao.setFont(font3)
        self.lb_bien_vao.setStyleSheet(u"background-color: rgb(255, 255, 255);")
        self.lb_bien_vao.setFrameShape(QFrame.Panel)
        self.lb_bien_vao.setAlignment(Qt.AlignCenter)
        self.lb_bien_ra = QLabel(self.centralwidget)
        self.lb_bien_ra.setObjectName(u"lb_bien_ra")
        self.lb_bien_ra.setGeometry(QRect(490, 490, 451, 71))
        self.lb_bien_ra.setFont(font3)
        self.lb_bien_ra.setStyleSheet(u"background-color: rgb(255, 255, 255);")
        self.lb_bien_ra.setFrameShape(QFrame.Panel)
        self.lb_bien_ra.setAlignment(Qt.AlignCenter)
        self.QUIT = QPushButton(self.centralwidget)
        self.QUIT.setObjectName(u"QUIT")
        self.QUIT.setGeometry(QRect(1190, 780, 181, 61))
        self.QUIT.setFont(font2)
        self.QUIT.setLayoutDirection(Qt.LeftToRight)
        self.QUIT.setAutoFillBackground(False)
        self.QUIT.setStyleSheet(u"color: rgb(0, 0, 0);\n"
"background-color: rgb(255, 0, 0);")
        self.label_14 = QLabel(self.centralwidget)
        self.label_14.setObjectName(u"label_14")
        self.label_14.setGeometry(QRect(20, 570, 111, 41))
        self.label_14.setFont(font4)
        self.label_14.setStyleSheet(u"background-color: rgb(255, 255, 255);\n"
"\n"
"")
        self.label_15 = QLabel(self.centralwidget)
        self.label_15.setObjectName(u"label_15")
        self.label_15.setGeometry(QRect(20, 620, 111, 41))
        self.label_15.setFont(font4)
        self.label_15.setStyleSheet(u"background-color: rgb(255, 255, 255);\n"
"\n"
"")
        self.label_16 = QLabel(self.centralwidget)
        self.label_16.setObjectName(u"label_16")
        self.label_16.setGeometry(QRect(20, 670, 111, 41))
        self.label_16.setFont(font4)
        self.label_16.setStyleSheet(u"background-color: rgb(255, 255, 255);\n"
"\n"
"")
        self.label_17 = QLabel(self.centralwidget)
        self.label_17.setObjectName(u"label_17")
        self.label_17.setGeometry(QRect(20, 720, 111, 41))
        self.label_17.setFont(font4)
        self.label_17.setStyleSheet(u"background-color: rgb(255, 255, 255);\n"
"\n"
"")
        self.lb_tgian_vao = QLabel(self.centralwidget)
        self.lb_tgian_vao.setObjectName(u"lb_tgian_vao")
        self.lb_tgian_vao.setGeometry(QRect(140, 570, 271, 41))
        font6 = QFont()
        font6.setFamilies([u"Arial"])
        font6.setPointSize(18)
        font6.setBold(True)
        self.lb_tgian_vao.setFont(font6)
        self.lb_tgian_vao.setStyleSheet(u"background-color: rgb(255, 255, 255);")
        self.lb_tgian_vao.setFrameShape(QFrame.Panel)
        self.lb_tgian_vao.setAlignment(Qt.AlignCenter)
        self.lb_tgian_ra = QLabel(self.centralwidget)
        self.lb_tgian_ra.setObjectName(u"lb_tgian_ra")
        self.lb_tgian_ra.setGeometry(QRect(140, 620, 271, 41))
        self.lb_tgian_ra.setFont(font6)
        self.lb_tgian_ra.setStyleSheet(u"background-color: rgb(255, 255, 255);")
        self.lb_tgian_ra.setFrameShape(QFrame.Panel)
        self.lb_tgian_ra.setAlignment(Qt.AlignCenter)
        self.lb_tgian_tong = QLabel(self.centralwidget)
        self.lb_tgian_tong.setObjectName(u"lb_tgian_tong")
        self.lb_tgian_tong.setGeometry(QRect(140, 670, 271, 41))
        self.lb_tgian_tong.setFont(font6)
        self.lb_tgian_tong.setStyleSheet(u"background-color: rgb(255, 255, 255);")
        self.lb_tgian_tong.setFrameShape(QFrame.Panel)
        self.lb_tgian_tong.setAlignment(Qt.AlignCenter)
        self.tien = QLabel(self.centralwidget)
        self.tien.setObjectName(u"tien")
        self.tien.setGeometry(QRect(140, 720, 271, 41))
        self.tien.setFont(font6)
        self.tien.setStyleSheet(u"background-color: rgb(255, 255, 255);")
        self.tien.setFrameShape(QFrame.Panel)
        self.tien.setAlignment(Qt.AlignCenter)
        self.LOG = QLabel(self.centralwidget)
        self.LOG.setObjectName(u"LOG")
        self.LOG.setGeometry(QRect(150, 780, 1031, 61))
        self.LOG.setFont(font6)
        self.LOG.setStyleSheet(u"background-color: rgb(255, 255, 255);")
        self.LOG.setFrameShape(QFrame.Panel)
        self.LOG.setAlignment(Qt.AlignCenter)
        self.label_19 = QLabel(self.centralwidget)
        self.label_19.setObjectName(u"label_19")
        self.label_19.setGeometry(QRect(20, 790, 111, 41))
        self.label_19.setFont(font4)
        self.label_19.setStyleSheet(u"background-color: rgb(255, 255, 255);\n"
"\n"
"")
        self.HISTORY = QPushButton(self.centralwidget)
        self.HISTORY.setObjectName(u"HISTORY")
        self.HISTORY.setGeometry(QRect(1190, 700, 181, 71))
        self.HISTORY.setFont(font2)
        self.HISTORY.setLayoutDirection(Qt.LeftToRight)
        self.HISTORY.setAutoFillBackground(False)
        self.HISTORY.setStyleSheet(u"color: rgb(0, 0, 0);\n"
"background-color: rgb(0, 255, 0);")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QMenuBar(MainWindow)
        self.menubar.setObjectName(u"menubar")
        self.menubar.setGeometry(QRect(0, 0, 1379, 21))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QStatusBar(MainWindow)
        self.statusbar.setObjectName(u"statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)

        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"MainWindow", None))
        self.btn_ref.setText(QCoreApplication.translate("MainWindow", u"T\u1ea2I L\u1ea0I", None))
        self.label.setText(QCoreApplication.translate("MainWindow", u"Camera", None))
        self.pick_cam.setItemText(0, QCoreApplication.translate("MainWindow", u"CAMERA_IN", None))
        self.pick_cam.setItemText(1, QCoreApplication.translate("MainWindow", u"CAMERA_OUT", None))
        self.pick_cam.setItemText(2, QCoreApplication.translate("MainWindow", u"CAMERA_CHECK", None))

        self.btn_start.setText(QCoreApplication.translate("MainWindow", u"Start", None))
        self.btn_stop.setText(QCoreApplication.translate("MainWindow", u"Stop", None))
        self.disp_main_in.setText(QCoreApplication.translate("MainWindow", u"CAMERA V\u00c0O", None))
        self.disp_main_check.setText(QCoreApplication.translate("MainWindow", u"CAMERA CHECK XE", None))
        self.disp_main_out.setText(QCoreApplication.translate("MainWindow", u"CAMERA RA", None))
        self.BT_VAO.setText(QCoreApplication.translate("MainWindow", u"V\u00c0O", None))
        self.BT_RA.setText(QCoreApplication.translate("MainWindow", u"RA", None))
        self.lb_con_lai.setText("")
        self.label_11.setText(QCoreApplication.translate("MainWindow", u"C\u00d2N L\u1ea0I", None))
        self.label_18.setText(QCoreApplication.translate("MainWindow", u"\u0110\u00c3 \u0110\u1ed6", None))
        self.lb_so_xe.setText("")
        self.lb_tb_2.setText(QCoreApplication.translate("MainWindow", u"C\u00d2N CH\u1ed6 TR\u1ed0NG", None))
        self.thoi_gian.setText("")
        self.lb_bien_vao.setText("")
        self.lb_bien_ra.setText("")
        self.QUIT.setText(QCoreApplication.translate("MainWindow", u"THO\u00c1T", None))
        self.label_14.setText(QCoreApplication.translate("MainWindow", u"V\u00c0O", None))
        self.label_15.setText(QCoreApplication.translate("MainWindow", u"RA", None))
        self.label_16.setText(QCoreApplication.translate("MainWindow", u"T\u1ed4NG ", None))
        self.label_17.setText(QCoreApplication.translate("MainWindow", u"TI\u1ec0N", None))
        self.lb_tgian_vao.setText("")
        self.lb_tgian_ra.setText("")
        self.lb_tgian_tong.setText("")
        self.tien.setText("")
        self.LOG.setText("")
        self.label_19.setText(QCoreApplication.translate("MainWindow", u"LOG", None))
        self.HISTORY.setText(QCoreApplication.translate("MainWindow", u"LOG", None))
    # retranslateUi

